import {combineReducers} from "redux"
import feedReducer from "./feedbackRedux/feedbackReducer"
import loginReducer from "./logRedux/loginReducer"
import aboutReducer from "./aboutRedux/aboutReducer"
import footerReducer from "./footerRedux/footerReducer"
import CareerReducer from "./careerRedux/careerReducer"
import EmployeeReducer from "./employeeRedux/EmployeeReducer"
import insightReducer from "./insightRedux/insightReducer"
import achieveReducer from "./achieveRedux/achieveReducer"
import jobReducer from "./jobRedux/jobReducer"
export const rootReducer = combineReducers({ EmployeeReducer,jobReducer,footerReducer,CareerReducer,loginReducer,achieveReducer,aboutReducer,insightReducer,feedReducer})